name: Release
on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Get release version
        id: get_version
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:10})

      - name: Build
        run: |
            make build
            echo "version: $$VERSION"

      - name: build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.REPO_USER}}
          password: ${{secrets.REPO_KEY}}
          registry: "quay.io"
          tag_with_ref: true
          dockerfile: cmd/provisioner/Dockerfile

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'vcd-csi'